name: Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  release:
    permissions:
      contents: write
    uses: lightwebinc/ci/.github/workflows/gh-release.yml@6477feb1c5a021d27e88d6891101095a1178cde9 # main
