name: Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  release:
    permissions:
      contents: write
    uses: lightwebinc/ci/.github/workflows/gh-release.yml@bfcf31c675b8206453c90497534a72886933f0a9 # main
